import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";

export const metadata: Metadata = {
  title: "Video Call Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center h-full">
        <main className="w-full max-w-5xl h-screen">
          <UserProvider>
            {children}
          </UserProvider>
        </main>
      </body>
    </html>
  );
}
